### PR TITLE
Added csharp code

### PR DESCRIPTION
**Pull request by areyohrahul**

### CODE REVIEW

**Comment by avinassh** [comment]
Is that full executable example? Please make it full code. I will be updating all other examples also. 

`"System.Console.WriteLine('Hello, World!');"`

**Comment by areyohrahul** [comment]
okay.

**Comment by avinassh** [comment]
Why `hello1`? And are you sure it requires `public`?

**Comment by areyohrahul** [comment]
Yeah I am sure. I checked it from https://msdn.microsoft.com/. Okay I will change hello1 to helloworld, although it does'nt make any difference in c#.

**Comment by avinassh** [comment]
`bash` already exists, thats why you are getting issues with merge now. Anyways I would suggest following C# code, straight from [Wikipedia](https://en.wikipedia.org/wiki/C_Sharp_%28programming_language%29#Examples):

```
using System;

class HelloWorld
{
    static void Main()
    {
        Console.WriteLine("Hello world");
    }
}
```

Since there are conflicts now, do this, 
- solve merge conflicts
- squash the commits and make it to a 'added C# examaple'

Sounds fine? Thanks for the PR!

**Comment by areyohrahul** [comment]
Okay I will do that.

**Comment by avinassh** [comment]
:+1:

**Pull request closed without merging**
