### PR TITLE
php deserves rockstars too

### PR DESCRIPTION
**Pull request by jarnix**
obviously

### CODE REVIEW

**Comment by avinassh** [comment]
I am not sure and I thought @MarkWaldron had intentionally left out php :grimacing:

**Comment by jarnix** [comment]
That's also what I thought :( lol.

**Comment by avinassh** [comment]
I am accepting the PR. Just received a call from Zuck.

**Comment by MarkWaldron** [comment]
@avinassh @jarnix I swear I didn't lol I just don't work with PHP very often

**Pull request merged**
