### PR TITLE
Add examples folder with example files for multiple languages

### PR DESCRIPTION
**Pull request by MarkWaldron**
Added a folder titled Examples that contains multiple example files. Each example file is for a different language, with the correct file extension.

### CODE REVIEW

**Comment by avinassh** [comment]
Thanks @MarkWaldron! Welcome to Rockstars Club :sunglasses:

**Comment by MarkWaldron** [comment]
@avinassh Thank you for the warm welcome!

**Comment by avinassh** [comment]
Hey. I just noticed that the example codes are not fully complete. For example, the C++ example should be:

```
from RockStar import RockStar

cpp_code = """#include <iostream>
int main()
{
  std::cout << "Hello World!";
}"""

rock_it_bro = RockStar(days=400, file_name='helloWorld.cpp', code=cpp_code)
rock_it_bro.make_me_a_rockstar()
```

Let me know if you are interested in updating them.

**Comment by MarkWaldron** [comment]
@avinassh I had just included one liners in each of the examples as a framework for future development. Are you working to implement semi-random code snippets for each language so the commits look more unique?

**Comment by avinassh** [comment]
Yup, it is being discussed at #10. However till that task is completed, I wanted to have complete examples of scripts/programs 

Also, next update will break the examples. I did not follow pep8 for rockstar package. It should be 

```
from rockstar import Rockstar
```

Instead of 

```
from Rockstar import Rockstar
```

I will update it here once it is done. and then we can update all the examples.

**Pull request merged**
