### PR TITLE
Rockstars use python3, rockstars use yield from

### PR DESCRIPTION
**Pull request by dinoshauer**
Embrace python3 like a real rockstar and use `yield from` :rocket: :star:

### CODE REVIEW

**Comment by avinassh** [comment]
Hey thanks for the PR! 

I totally agree that rockstars use `yield`, but the guys who built the [progress bar](https://github.com/verigak/progress/) I use aren't rockstar enough, so the progress bar ends abruptly when `yield` is used. 

jokes aside, the progress bar library I used needs to know the number of items in the list before hand without that the progress bar never reaches 100%. Earlier I did use generator objects, but due to this I went with the list. This is how it looks:

new pr

You can check this locally also. I will look into this and see if its possible to fix it.

**Comment by dinoshauer** [comment]
Weird. I didn't run into this when I tested the PR. Makes sense that the
bar needs to know the length though :)

**Comment by avinassh** [comment]
Test with longer days, something like 80.

**Comment by avinassh** [comment]
So I will close this PR now, but I will update here if I find anything :)

**Comment by dinoshauer** [comment]
No worries. If you use `click` instead you can do it with a generator and update the bar manually, it should be feasible to figure out how many items are in the generator. And it'd take care of #4 :)

I could probably do a quick PR on it

**Comment by avinassh** [comment]
#20 completes this :+1:

**Pull request closed without merging**
