### PR TITLE
Added many examples.

### PR DESCRIPTION
**Pull request by duaneking**
A lot of people don't respect the classics these days, so it takes a true artist to have the appreciation for the masters and works that came before.

Since a true rock-star knows his history I felt it best to acknowledge that with this addition.

### CODE REVIEW

**Comment by avinassh** [comment]
Ha ha, you are on a roll @duaneking Thanks for this great PR. I see you are updating it constantly. Let me know once you are done and I will merge. 

If possible please [squash your commits make it a single commit](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git).

**Comment by duaneking** [comment]
I decided to add a few more modern languages as well.. not done yet, will update when I am.

**Comment by duaneking** [comment]
I cnat help but wonder where the merge issues came from?

**Comment by avinassh** [comment]
Some conflicts have shown up. Probably because I accepted other PRs. You need to do rebase with master.

**Comment by duaneking** [comment]
Ok looks like your merge of another DART example created issues I will remove my dart example to make the merge easy.

**Comment by duaneking** [comment]
Please accept pull request as with the removal of the Dart example I added it can be merged without conflicts.

**Comment by duaneking** [comment]
Its 12:30am here so I am tired and need to get to bed, please consider this pull request done.

**Comment by avinassh** [comment]
Thanks Duane, merged! :smile:

**Pull request merged**
